# Generated by Django 4.1 on 2022-09-06 00:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_alter_incidences_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gm',
            name='location',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidences',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
